# Generated by Django 4.1 on 2022-10-20 20:51

from django.db import migrations, models
import django.db.models.deletion
import semglu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('idBrand', models.BigAutoField(primary_key=True, serialize=False)),
                ('brandName', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200, null=True)),
                ('logoPath', models.ImageField(max_length=500, null=True, upload_to=semglu.models.Brand.update_file_path)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('barCode', models.BigAutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=200)),
                ('productCategory', models.CharField(max_length=200, null=True)),
                ('picturePath', models.ImageField(max_length=500, null=True, upload_to=semglu.models.Product.update_file_path)),
                ('productIngredients', models.TextField(null=True)),
                ('createdAt', models.DateTimeField(null=True)),
                ('idBrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='semglu.brand')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('idReport', models.BigAutoField(primary_key=True, serialize=False)),
                ('filePath', models.FileField(max_length=500, null=True, upload_to=semglu.models.Report.update_file_path)),
                ('createdAt', models.DateTimeField(null=True)),
                ('expiredAt', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='Safety',
            fields=[
                ('idSafety', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'safety',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.BigAutoField(primary_key=True, serialize=False)),
                ('nick', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('idReview', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('grade', models.FloatField()),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='semglu.product')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='semglu.user')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='idReport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='semglu.report'),
        ),
        migrations.AddField(
            model_name='product',
            name='idSafety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='semglu.safety'),
        ),
    ]
