# Generated by Django 4.1 on 2022-09-22 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('idBrand', models.BigAutoField(default=1, primary_key=True, serialize=False)),
                ('brandName', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('logoPath', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('idReport', models.BigAutoField(default=1, primary_key=True, serialize=False)),
                ('filePath', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField()),
                ('expiredAt', models.DateTimeField()),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='Safety',
            fields=[
                ('idSafety', models.BigAutoField(default=1, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'safety',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.BigAutoField(default=1, primary_key=True, serialize=False)),
                ('nick', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('barCode', models.BigAutoField(default=1, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=200)),
                ('productCategory', models.CharField(max_length=200)),
                ('picturePath', models.ImageField(upload_to='products')),
                ('productIngredients', models.CharField(max_length=500)),
                ('createdAt', models.DateTimeField()),
                ('idBrand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='semglu.brand')),
                ('idReport', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='semglu.report')),
                ('idSafety', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='semglu.safety')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
