# Generated by Django 4.1 on 2022-09-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semglu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='idBrand',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='barCode',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='idReport',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='safety',
            name='idSafety',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='idUser',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
