# Generated by Django 4.1 on 2022-09-22 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semglu', '0002_alter_brand_idbrand_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logoPath',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='idBrand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='semglu.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='idReport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='semglu.report'),
        ),
        migrations.AlterField(
            model_name='product',
            name='idSafety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='semglu.safety'),
        ),
        migrations.AlterField(
            model_name='safety',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
