# Generated by Django 4.1 on 2022-09-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semglu', '0003_alter_brand_contact_alter_brand_logopath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picturePath',
            field=models.ImageField(upload_to='media/picture'),
        ),
    ]
