# Generated by Django 4.1 on 2022-09-04 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semglu', '0003_product_idbrand_product_idreport_product_idsafety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='idSafety',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='semglu.safety'),
        ),
    ]
