# Generated by Django 4.1 on 2022-09-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semglu', '0005_alter_product_picturepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logoPath',
            field=models.ImageField(upload_to='logo'),
        ),
    ]
