# Generated by Django 4.1 on 2022-09-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semglu', '0006_alter_brand_logopath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='filePath',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
