# Generated by Django 4.1 on 2022-09-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semglu', '0007_alter_report_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='filePath',
            field=models.FileField(upload_to='reports'),
        ),
    ]
