# Generated by Django 4.1 on 2022-10-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semglu', '0008_alter_report_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logoPath',
            field=models.ImageField(max_length=500, upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picturePath',
            field=models.ImageField(max_length=500, upload_to='picture'),
        ),
        migrations.AlterField(
            model_name='report',
            name='filePath',
            field=models.FileField(max_length=500, upload_to='reports'),
        ),
    ]
