# Generated by Django 4.1 on 2022-10-01 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semglu', '0009_alter_brand_logopath_alter_product_picturepath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='contact',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logoPath',
            field=models.ImageField(max_length=500, null=True, upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='createdAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='idReport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='semglu.report'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picturePath',
            field=models.ImageField(max_length=500, null=True, upload_to='picture'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productCategory',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productIngredients',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='createdAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='expiredAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='filePath',
            field=models.FileField(max_length=500, null=True, upload_to='reports'),
        ),
        migrations.AlterField(
            model_name='safety',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdAt',
            field=models.DateTimeField(null=True),
        ),
    ]
