# Generated by Django 4.1 on 2022-10-14 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semglu', '0011_alter_product_productingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('idReview', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('grade', models.FloatField()),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='semglu.product')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='semglu.user')),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
